toolshare/toolshare/urls.py
from django.contrib import admin
from django.urls import path
from authentication import views as authView
from blog import views as blogView
from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # Home / About / Contact / Publisher
    path('', authView.Home.as_view(template_name='authentication/home.html'), name='home'),
    path('user/<int:userID>/contract/<int:contractID>/pdf/', blogView.borrowContractPDF.as_view(template_name='blog/borrowContract.html'), name='borrowContract'),
    path('user/<int:userID>/about/', authView.About.as_view(template_name='authentication/about.html'), name='about'),
    path('user/<int:userID>/contact/', authView.Contact.as_view(template_name='authentication/contact.html'), name='contact'),
    path('user/<int:userID>/contact/success/', authView.Contact.as_view(template_name='authentication/contactSuccess.html'), name='contact-success'),
    path('user/<int:userID>/publisher/', authView.Publisher.as_view(template_name='authentication/publisher.html'), name='publisher'),
    # Research
    path('user/<int:userID>/research/', authView.Research.as_view(template_name='authentication/research.html'), name='research'),
    path('user/<int:userID>/research/all-tools/', authView.Research.as_view(template_name='authentication/research.html'), name='research-all-tools'),
    path('user/<int:userID>/research/all-equipments/', authView.Research.as_view(template_name='authentication/research.html'), name='research-all-equipments'),
    path('user/<int:userID>/research/most-popular/', authView.Research.as_view(template_name='authentication/research.html'), name='research-most-popular'),
    path('user/<int:userID>/research/best-rated/', authView.Research.as_view(template_name='authentication/research.html'), name='research-best-rated'),
    # /Research
    path('user/<int:userID>/favorites/', authView.Favorites.as_view(template_name='authentication/favorites.html'), name='favorites'),
    path('user/<int:userID>/profile/', authView.Profile.as_view(template_name='authentication/profile.html'), name='profile'),
    path('user/<int:userID>/member/<int:memberID>/member-profile/', authView.memberProfile.as_view(template_name='authentication/profile.html'), name='member-profile'),
    path('user/<int:userID>/edit-profile/', authView.editProfile.as_view(template_name='authentication/editProfile.html'), name='edit-profile'),
    path('user/<int:userID>/edit-tool/', blogView.editTool.as_view(template_name='blog/editTool.html'), name='edit-tool'),
    path('user/<int:userID>/personal-tools/', blogView.personalTools.as_view(template_name='blog/personalTools.html'), name='personal-tools'),
    path('user/<int:userID>/member/<int:memberID>/member-tools/', blogView.memberTools.as_view(template_name='blog/personalTools.html'), name='member-tools'),
    path('registration/', authView.Registration.as_view(template_name='authentication/registration.html'), name='registration'),
    path('user/<int:userID>/tool/<int:toolID>/details/', blogView.toolDetails.as_view(template_name='blog/toolDetails.html'), name='tool-details'),
    path('user/<int:userID>/tool/<int:toolID>/details/borrow-request-contract/', blogView.borrowRequestForm.as_view(template_name='blog/borrowRequestForm.html'), name='borrow-request-form'),
    path('user/<int:userID>/tool/<int:toolID>/details/borrow-request-confirmation/', blogView.borrowRequestConfirmation.as_view(template_name='blog/borrowRequestConfirmation.html'), name='borrow-request-confirmation'),
    path('user/<int:userID>/contract/<int:contractID>/consent-to-borrow-contract/', blogView.consentToBorrowForm.as_view(template_name='blog/consentToBorrowForm.html'), name='consent-to-borrow-form'),
    path('user/<int:userID>/contract/<int:contractID>/consent-to-borrow-confirmation/', blogView.consentToBorrowConfirmation.as_view(template_name='blog/consentToBorrowConfirmation.html'), name='consent-to-borrow-confirmation'),

    # Login / Logout / Change Password Urls
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html',
         redirect_authenticated_user=True),
         name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('change-password/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change_form.html'),
         name='password_change'),
    path('change-password-done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'),
         name='password_change_done'),

    # Reset Password Urls
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

toolshare/blog/models.py
from django.conf import settings
from django.db import models
from datetime import date, timedelta
from django.core.validators import MinValueValidator
from jsignature.fields import JSignatureField


# Create your models here.
def oneDayHence():
    return date.today() + timedelta(days=1)


class Blog(models.Model):
    name = models.CharField(max_length=128,)
    image = models.ImageField(default='userPersonalToolPicture/defaultPersonalToolPicture.png', upload_to='userPersonalToolPicture')
    CATEGORY_CHOICES = [
        ("Carpentry work", "Carpentry work"),
        ("Secondary work", "Secondary work"),
        ("Finishing work", "Finishing work"),
        ("Motoculture maintenance", "Motoculture maintenance"),
        ("Green space maintenance", "Green space maintenance"),
        ("Equipment", "Equipment"),
        ("Other", "Other"),
    ]
    category = models.CharField(max_length=128, choices=CATEGORY_CHOICES)
    location = models.CharField(max_length=128,)
    description = models.TextField(max_length=2048)
    availabalityStart = models.DateField(default=date.today, validators=[MinValueValidator(limit_value=date.today)])
    availabalityEnd = models.DateField(default=oneDayHence, validators=[MinValueValidator(limit_value=oneDayHence)])
    availabality = models.BooleanField(default=True)
    deposit = models.BooleanField(default=False)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)
    popularity = models.IntegerField(default=0)
    match = models.BooleanField(default=False)
    onContract = models.BooleanField(default=False)


class Favorite(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='user_favorite', on_delete=models.CASCADE)
    blog = models.ForeignKey(Blog, related_name='favorites', on_delete=models.CASCADE)

    class Meta:
        ordering = ['id']

    def __str__(self):
        return f'{self.user}'


class SignatureModel(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='user_signature', on_delete=models.CASCADE)
    signature = JSignatureField()


class Contract(models.Model):
    applicant = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='applicant', on_delete=models.CASCADE)
    supplier = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='supplier', on_delete=models.CASCADE, null=True)
    applicantName = models.CharField(max_length=128,)
    supplierName = models.CharField(max_length=128, null=True)
    contractedBlog = models.ForeignKey(Blog, related_name='contracted_tool', on_delete=models.CASCADE)
    applicantApproval = models.CharField(max_length=63)
    supplierApproval = models.CharField(max_length=63, null=True)
    applicantPostalAddress = models.CharField(max_length=127)
    supplierPostalAddress = models.CharField(max_length=127, null=True)
    applicantSignature = models.ForeignKey(SignatureModel, related_name='applicant_signature', on_delete=models.CASCADE)
    supplierSignature = models.ForeignKey(SignatureModel, related_name='supplier_signature', on_delete=models.CASCADE, null=True)
    requestDate = models.DateField(default=date.today,)
    approvalDate = models.DateField(default=date.today, null=True)
    startOfUse = models.DateField(default=date.today, validators=[MinValueValidator(limit_value=date.today)])
    endOfUse = models.DateField(validators=[MinValueValidator(limit_value=date.today)])

toolshare/blog/forms.py
# blog/forms.py
from django import forms
from . import models
from jsignature.forms import JSignatureField
from jsignature.widgets import JSignatureWidget


class BlogForm(forms.ModelForm):
    class Meta:
        model = models.Blog
        fields = ['name', 'image', 'category', 'description', 'location', 'availabalityStart', 'availabalityEnd', 'deposit']


class SignatureForm(forms.Form):
    signature = JSignatureField(widget=JSignatureWidget(jsignature_attrs={'width': '350px', 'height': '150px'}))


class ApplicantContractForm(forms.ModelForm):
    class Meta:
        model = models.Contract
        fields = "__all__"
        exclude = ('applicant', 'supplier', 'supplierName', 'contractedBlog', 'supplierApproval', 'supplierPostalAddress', 'applicantSignature', 'supplierSignature', 'approvalDate')


class SupplierContractForm(forms.ModelForm):
    class Meta:
        model = models.Contract
        fields = "__all__"
        exclude = ('applicant', 'supplier', 'applicantName', 'contractedBlog', 'applicantApproval', 'applicantPostalAddress', 'applicantSignature', 'supplierSignature', 'requestDate', 'startOfUse', 'endOfUse')

toolshare/blog/templates/blog/borrowContract.html
{% load jsignature_filters %}

<title>ToolShare</title>

<div style="font-size: x-large">
    <p style="text-align: right;">Done on {{ contractInfo.creationDate }}</p>

    <br>

    <h1 style="text-align: center;">CONTRACT No. {{ contractInfo.contractID }}</h1>

    <br>
    <br>

    <h3 style="text-decoration: underline;">Borrowing Conditions:</h3>

    <ul>
        <li>Commit to respecting the equipment</li>
        <li>Commit to returning the equipment clean and with a full tank</li>
        <li>Commit to notifying the owner in case of equipment failure during use</li>
        <li>Commit not to lend/sublet/sell the equipment</li>
        <li>Commit to being the sole user of the equipment</li>
        <li>Commit to using the equipment only on a personal construction site</li>
        <li>Commit to using the equipment only for its intended purpose</li>
        <li>Commit to respecting deadlines</li>
        <li>Commit to wearing the necessary safety equipment while using the equipment</li>
        <li>Commit to reimbursing for equipment damage or loss</li>
        <li>Commit not to file a complaint in case of accidents caused by human error</li>
    </ul>
    <p>In case of non-compliance with these conditions, a penalty or legal action will be applied.</p>

    <p>- The applicant named <span style="font-weight: bold;">{{ contractInfo.applicantName }}</span> confirms having
        <span style="font-weight: bold;">{{ contractInfo.applicantApproval }}</span> the borrowing conditions <br>on
        <span style="font-weight: bold;">{{ contractInfo.requestDate }}</span> at <span style="font-weight: bold;">{{ contractInfo.applicantPostalAddress }}</span>.</p>

    <br>

    <div style="margin-left: 500px;">
        <p style="text-decoration: underline;">Applicant Signature:</p>
        <div style="height: 120px; width: 200px; border: 1px solid black;"><img
                src="{{ contractInfo.applicantSignature.signature|signature_base64 }}" /></div>
    </div>

    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>

    <h3 style="text-decoration: underline;">Lending Conditions:</h3>

    <ul>
        <li>Commit to lending the equipment in good condition, clean, and with a full tank</li>
        <li>Commit to respecting deadlines</li>
        <li>Commit to returning the deposit if the equipment's integrity is maintained</li>
        <li>Commit to informing the borrower if the equipment has been modified</li>
        <li>Commit to explaining the equipment's operation</li>
        <li>Commit to being honest about the equipment's condition during handover</li>
    </ul>
    <p>In case of non-compliance with these conditions, a penalty or legal action will be applied.</p>

    <p>- The supplier named <span style="font-weight: bold;">{{ contractInfo.supplierName }}</span> confirms having
        <span style="font-weight: bold;">{{ contractInfo.supplierApproval }}</span> the lending conditions <br>on <span
            style="font-weight: bold;">{{ contractInfo.approvalDate }}</span> at <span style="font-weight: bold;">{{ contractInfo.supplierPostalAddress }}</span>.</p>

    <br>

    <div style="margin-left: 500px;">
        <p style="text-decoration: underline;">Supplier Signature:</p>
        <div style="height: 120px; width: 200px; border: 1px solid black;"><img
                src="{{ contractInfo.supplierSignature.signature|signature_base64 }}" /></div>
    </div>

    <br>
    <br>
    <br>
    <br>

    <p>The tool <span style="font-weight: bold;">{{ contractInfo.contractedBlog.name }}</span> will be borrowed/lent
        from <span style="font-weight: bold;">{{ contractInfo.startOfUse }}</span> to <span
            style="font-weight: bold;">{{ contractInfo.endOfUse }}</span>.</p>
    {% if user.id == contractInfo.applicant.id %}
    <p>To arrange a meeting place, please contact the supplier at the following e-mail address: <span style="font-weight: bold;">{{ contractInfo.supplier.email }}</span></p>
    {% elif user.id == contractInfo.supplier.id %}
    <p>To arrange a meeting place, please contact the borrower at the following e-mail address: <span style="font-weight: bold;">{{ contractInfo.applicant.email }}</span></p>
    {% endif %}
    
</div>

toolshare/blog/templates/blog/borrowContractLink.html
<p>Hello, the contract has been confirmed !<br>
Click here to access to the PDF Contract : <a href="https://example.com{% url 'borrowContract' userID contractID %}">PDF Contract</a></p>

toolshare/blog/templates/blog/borrowRequest.html
{% extends 'authentication/base.html' %}

{% load widget_tweaks %}

{% block content %}

<style>
    .gradient-custom {
        background: linear-gradient(112.1deg, rgb(32, 38, 57) 11.4%, rgb(63, 76, 119) 70.2%);
    }
    .jSignature {
        border: 1px solid rgb(51, 51, 51, 0.5) !important;
        max-width: 100%;
    }
    input {
        padding-left: 5px;
        margin: 0 3px 0 3px;
    }
    [value="Reset"] {
        margin-top: 2px;
        border: 1px solid rgb(51, 51, 51, 0.5) !important;
    }
    [value="Reset"]:hover {
        color: white;
        background-color: gray;
    }
    .jsign-wrapper {
        display: flex;
        flex-direction: column;
        align-items: center;
    }
</style>

<section class="h-100 gradient-custom">
    <div class="container py-5 w-100">
        <div class="row flex-lg-nowrap">
            <div class="col mb-3">
                <div class="card shadow">
                    <div class="card-body">
                        <div class="e-profile">
                            <h1>Contract</h1>
                            <h5>Conditions d'utilisation</h5>
                            <form action="" method="post">
                                {% csrf_token %}
                                <p class="text-end">Je soussigné : {% render_field form.fullname placeholder=user.fullname %}
                                    avoir {% render_field form.approval placeholder="Lu et approuvé" %}
                                    le {% render_field form.date type="date" %}
                                    à {% render_field form.postalAddress placeholder=user.postalAddress %}.
                                </p>
                                <div class="d-flex justify-content-end">
                                    <div class="d-flex flex-column">
                                        <label class="form-label fw-bold mt-3" for="id_signature">Signature :</label>
                                        {{ form.signature }}
                                        {{ form.media }}
                                    </div>
                                </div>
                                <p class="text-center"><button class="btn btn-outline-primary" type="submit" name="sendContract">Send</button></p>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

toolshare/blog/templates/blog/borrowRequestConfirmation.html
{% extends 'authentication/base.html' %}

{% load widget_tweaks %}
{% load jsignature_filters %}

{% block content %}

<style>
    .gradient-custom {
        background: linear-gradient(112.1deg, rgb(32, 38, 57) 11.4%, rgb(63, 76, 119) 70.2%);
    }
    body {
        height: 700px;
    }
</style>


<section class="vh-100 gradient-custom">
    <div class="container h-100 d-flex align-items-center justify-content-center">
        <div class="row flex-lg-nowrap">
            <div class="col mb-5">
                <div class="card shadow bg-dark text-white" style="border-radius: 1rem;">
                    <div class="card-body p-5">
                        <div class="text-center">
                            <h3 class="fw-bold text-uppercase">Your request has been sent</h3>
                            <p class="fs-5 mt-4"><a class="text-white-50" href="{% url 'home' %}">Back to home page</a></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

toolshare/blog/templates/blog/borrowRequestForm.html
{% extends 'authentication/base.html' %}

{% load widget_tweaks %}
{% load jsignature_filters %}

{% block content %}

<style>
    .gradient-custom {
        background: linear-gradient(112.1deg, rgb(32, 38, 57) 11.4%, rgb(63, 76, 119) 70.2%);
    }
    .jSignature {
        border: 1px solid rgb(51, 51, 51, 0.5) !important;
        max-width: 100%;
    }
    input {
        padding-left: 5px;
        margin: 0 3px 0 3px;
    }
    [value="Reset"] {
        margin-top: 2px;
        border: 1px solid rgb(51, 51, 51, 0.5) !important;
    }
    [value="Reset"]:hover {
        color: white;
        background-color: gray;
    }
    .jsign-wrapper {
        display: flex;
        flex-direction: column;
        align-items: center;
    }
</style>


<section class="h-100 gradient-custom">
    <div class="container py-5 w-100">
        <div class="row flex-lg-nowrap">
            <div class="col mb-3">
                <div class="card shadow">
                    <div class="card-body p-5">
                        <div class="e-profile">
                            <h1 class="pb-1">Contract</h1>
                            <h5>Borrowing Conditions:</h5>
                            <div>
                                <ul>
                                    <li>Commit to respecting the equipment</li>
                                    <li>Commit to returning the equipment clean and with a full tank</li>
                                    <li>Commit to notifying the owner in case of equipment failure during use</li>
                                    <li>Commit not to lend/sublet/sell the equipment</li>
                                    <li>Commit to being the sole user of the equipment</li>
                                    <li>Commit to using the equipment only on a personal construction site</li>
                                    <li>Commit to using the equipment only for its intended purpose</li>
                                    <li>Commit to respecting deadlines</li>
                                    <li>Commit to wearing the necessary safety equipment while using the equipment</li>
                                    <li>Commit to reimbursing for equipment damage or loss</li>
                                    <li>Commit not to file a complaint in case of accidents caused by human error</li>
                                </ul>
                                <p>In case of non-compliance with these conditions, a penalty or legal action will be applied.</p>
                            </div>
                            <form class="pt-5" action="" method="post">
                                {% csrf_token %}
                                <div class="d-flex flex-column align-items-end">
                                    {% if form.errors %}
                                    {{ form.errors }}
                                    {% endif %}
                                    <p>Hello, I would like to borrow the tool "<a href="{% url 'tool-details' user.id tool.id %}" target="_blank"
                                            style="color: black;">{{ tool.name }}</a>" from {% render_field form.startOfUse name="startOfUse" type="date" %}
                                        to <span class="d-inline-flex flex-column">{% render_field form.endOfUse name="endOfUse" type="date" %}<spam class="ms-2">(max : {{ tool.availabalityEnd }})</spam></span>.</p>
                                    <p>I, the undersigned: {% render_field form.applicantName name="applicantName" placeholder=user.fullname %}
                                        have {% render_field form.applicantApproval name="applicantApproval" placeholder="Read and approved" %} the terms of borrowing
                                        on {% render_field form.requestDate name="requestDate" type="date" %}
                                        at {% render_field form.applicantPostalAddress name="applicantPostalAddress" placeholder=user.postalAddress %}.
                                    </p>
                                </div>
                                <div class="d-flex justify-content-end">
                                    <div class="d-flex flex-column">
                                        <label class="form-label fw-bold mt-3" for="id_signature">Signature :</label>
                                        {{ formSignature.media }}
                                        {{ formSignature.signature }}
                                    </div>
                                </div>
                                <p class="text-center mt-5"><button class="btn btn-outline-primary" type="submit" name="sendContract">Send</button></p>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

toolshare/blog/templates/blog/consentToBorrowConfirmation.html
{% extends 'authentication/base.html' %}

{% load widget_tweaks %}
{% load jsignature_filters %}

{% block content %}

<style>
    .gradient-custom {
        background: linear-gradient(112.1deg, rgb(32, 38, 57) 11.4%, rgb(63, 76, 119) 70.2%);
    }

    body {
        height: 700px;
    }
</style>


<section class="vh-100 gradient-custom">
    <div class="container h-100 d-flex align-items-center justify-content-center">
        <div class="row flex-lg-nowrap">
            <div class="col mb-5">
                <div class="card shadow bg-dark text-white" style="border-radius: 1rem;">
                    <div class="card-body p-5">
                        <div class="text-center">
                            {% if exists == True %}
                            <h3 class="fw-bold text-uppercase">A summary of the contract with the two signed parts<br>has been sent to you by e-mail.</h3>
                            {% else %}
                            <h3 class="fw-bold text-uppercase">Confirmation of your declination on this contract.</h3>
                            {% endif %}
                            <p class="fs-5 mt-4"><a class="text-white-50" href="{% url 'home' %}">Back to home page</a></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

toolshare/blog/templates/blog/consentToBorrowLink.html
<p>Hello, a user has requested a borrow !<br>
Click here to access the form : <a href="https://example.com{% url 'consent-to-borrow-form' userID contractID %}">Consent Form</a></p>

toolshare/blog/templates/blog/editTool.html
{% extends 'authentication/base.html' %}

{% load widget_tweaks %}

{% block content %}

<style>
    .gradient-custom {
        /* fallback for old browsers */
        background: #fbc2eb;

        /* Chrome 10-25, Safari 5.1-6 */
        background: -webkit-linear-gradient(to right, rgba(251, 194, 235, 1), rgba(166, 193, 238, 1));

        /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
        background: linear-gradient(to right, rgba(251, 194, 235, 1), rgba(166, 193, 238, 1))
    }
</style>

<section class="h-100 gradient-custom">
    <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col col-lg-9 col-xl-7">
                <div class="card shadow" style="background-color: #f8f9fa;">
                    <div class="rounded-top text-white d-flex flex-row align-items-center justify-content-center" style="background-color: #000; height: 200px;">
                        <p class="fs-2">Edit Your Tool</p>
                    </div>
                    {% if blog_form.errors %}
                    {{ blog_form.errors }}
                    {% endif %}
                    <form method="post" enctype="multipart/form-data" novalidate>
                        {% csrf_token %}
                        <div class="d-flex flex-column align-items-start align-items-md-center px-5 pt-5">
                            <div class="col-md-6 mb-4">
                                <div class="form-outline">
                                    <label class="form-label fw-bold" for="id_name">Name</label>
                                    {% render_field blog_form.name|attr:"autofocus" placeholder="Name" class+="form-control form-control-lg" %}
                                </div>
                            </div>
                            <div class="col-md-6 mb-4">
                                <div class="form-outline d-flex flex-column">
                                    <label class="form-label fw-bold" for="id_image">Image</label>
                                    {% render_field blog_form.image class+="form-control form-control-lg" %}
                                </div>
                            </div>
                            <div class="col-md-6 mb-4">
                                <div class="form-outline">
                                    <label class="form-label fw-bold" for="id_category">Category</label>
                                    {% render_field blog_form.category class+="form-control form-control-lg" %}
                                </div>
                            </div>
                            <div class="col-md-6 mb-4">
                                <div class="form-outline">
                                    <label class="form-label fw-bold" for="id_description">Description</label>
                                    {% render_field blog_form.description placeholder="Few words for discribe your tool" rows="5" class+="form-control form-control-lg" %}
                                </div>
                            </div>
                            <div class="col-md-6 mb-4">
                                <div class="form-outline">
                                    <label class="form-label fw-bold" for="id_location">Location</label>
                                    {% render_field blog_form.location placeholder="Noelle Adams 6351 Fringilla Avenue Gardena Colorado 37547 (559) 104-5475" class+="form-control form-control-lg" %}
                                </div>
                            </div>
                            <div class="col-md-6 mb-4">
                                <div class="form-outline">
                                    <label class="form-label fw-bold" for="id_availabalityStart">Availabality Start</label>
                                    {% render_field blog_form.availabalityStart class+="form-control form-control-lg" type="date" %}
                                </div>
                            </div>
                            <div class="col-md-6 mb-4">
                                <div class="form-outline">
                                    <label class="form-label fw-bold" for="id_availabalityEnd">Availabality End<br>
                                    (min 24h from today)</label>
                                    {% render_field blog_form.availabalityEnd class+="form-control form-control-lg" type="date" %}
                                </div>
                            </div>
                            <div class="col-md-6 mb-4">
                                <div class="form-outline">
                                    <label class="form-label fw-bold" for="id_deposit">Deposit :</label>
                                    {% render_field blog_form.deposit class+="ms-1" style="position: relative; top: 1px;" %}
                                </div>
                            </div>
                        </div>
                        <div class="d-flex flex-column align-items-center mb-5">
                            <button type="submit" class="btn btn-outline-dark px-4">
                                Create
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}